### ISSUE TITLE
1.0.1 version is not showing up as 1.0.1 in sketch.

### ISSUE THREAD

**Issue by dferrof1** [mattmcmanus/select-group-layers-sketch-plugin#11]
I tried several different installs. I deleted old version, downloaded new, did install from sketch. It keeps saying the version installed is 1.0.0, says update is available.

**Comment by mattmcmanus** [comment]
Yeah. I've noticed that as well. Not sure why that was happening. 

I just tried to publish a new version. Hopefully that clears it up? Let me know.

**Comment by mattmcmanus** [comment]
I'm going to close this for now. Let me know if I should reopen
