### ISSUE TITLE
Not working in Sketch 3.4

### ISSUE THREAD

**Issue by badyqb** [mattmcmanus/select-group-layers-sketch-plugin#5]
I just downloaded the latest sketch update but it seems this plugin stop working.
Try to remapped it manually to Cmd+Alt+E but it seems not working too.
I wonder if anyone can have a solution to this?

Thanks!

**Comment by mattmcmanus** [comment]
Hey, it might take me some time to get to this. Just had a kid!
On Mon, Oct 26, 2015 at 10:58 PM Bady <notifications@github.com> wrote:

> I just downloaded the latest sketch update but it seems this plugin stop
> working.
> Try to remapped it manually to Cmd+Alt+E but it seems not working too.
> I wonder if anyone can have a solution to this?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattmcmanus/select-group-layers-sketch-plugin/issues/5>
> .
>
-- 

*Matt McManus*
Independent Developer, Designer & Technical Advocate
(215) 565-5379
http://mcmanus.io

**Comment by badyqb** [comment]
@mattmcmanus no worries & congrats for that! 
Just FYI: same command is built inside the sketch here http://d.pr/i/10qfv
