### ISSUE TITLE
Not working in sketch 3.5

### ISSUE THREAD

**Issue by badyqb** [mattmcmanus/select-group-layers-sketch-plugin#6]
Hopefully you will have time to fix :)

**Comment by mattmcmanus** [comment]
Hey there, could you give me some details about how your installed it and how it's not working? I just tested with my installation on `3.5.1` and everything worked great. 

For reference, here is how my install looks:

<img width="914" alt="screen shot 2016-02-06 at 1 03 49 pm" src="https://cloud.githubusercontent.com/assets/9383/12868336/37bf249a-ccd2-11e5-9de4-c9010f8ec0ec.png">
![screen shot 2016-02-06 at 1 04 09 pm](https://cloud.githubusercontent.com/assets/9383/12868337/37c6f580-ccd2-11e5-8752-ff18ea66ad0a.png)

**Comment by badyqb** [comment]
@mattmcmanus just tried it again and it works now :grin: 
Thanks for the update matt! a time saver!
