### ISSUE TITLE
Broken in 3.9 (beta)

### ISSUE THREAD

**Issue by sogen** [mattmcmanus/select-group-layers-sketch-plugin#7]
Hi, FYI the plugin stopped working in 3.9
in 3.8.3 (latest stable version) still works fine

**Comment by skacperski** [comment]
Yep, it's not working in 3.9

**Comment by jshuaf** [comment]
For all who are interested, I patched it in my own plugin. See [here](https://github.com/jshuaf/select-children).

**Comment by sogen** [comment]
Is this a fork?

**Comment by mattmcmanus** [comment]
Sorry for the slow reply. I've not had a chance to figure out what has changed. 

@jshuaf Looks like you're using the same code as me. If you forked and PR'ed, I'd gladly merge it in.

**Comment by mattmcmanus** [comment]
I finally got around to updating the plugin. It should work the way you expect in the newest version of Sketch.
